---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## DSCE Business Analytics Conclave Workshop

19th, 20th & 21st April, 2pm - 5pm

## Introduction

Materials for the workshop. Please install all the required softwares and
download the data sets and scripts from this repository before the
workshop. 

## Software Prerequisites

### R

R can be installed from the R project [website](https://cran.r-project.org/).
Please install the latest version 3.4.4. 

### RStudio

RStudio IDE can be installed from the RStudio [website](https://www.rstudio.com/products/rstudio/download/). Install the free
desktopo version.

### R Packages

Below are a list of R packages required for the workshop. In the below video, we
show how to install the first package. To install the rest of the packages,
replace the name of the package.

### Anaconda

Download and install the Anaconda distribution from their [website](https://www.anaconda.com/download/). We will use [Jupyter Notebook](http://jupyter.org/) for the python session.

## R Session

- Quick tour of R & RStudio
- Importing data into R
- Data Wrangling
- Data Visualization
- Building Reports
- Exploratory Data Analysis
- Linear Regression
- Logistic Regression

## Python Session

- Data Wrangling with Pandas
- Data Visualization 
    - matplotlib
    - bokeh
    - plotly
- Modeling with statsmodels